const DOMSelectors = {
    card: document.querySelector(".card"),
    link: document.querySelectorAll(".link"),
    form1: document.querySelector(".Types"),
    form2: document.querySelector(".Berries"),
    form3: document.querySelector(".Region"),
    form: document.querySelector(".Main"),
    logo:document.querySelector(".logo"),
    buttonFlip: document.querySelector(".Page"),
    form4: document.querySelector(".next1"),
    form5: document.querySelector(".next2"),
    form6: document.querySelector(".next3"),
    form7: document.querySelector(".next4"),
    search: document.querySelector("#form"),
    input: document.querySelector(".pokemon"),
    h1:document.querySelectorAll("h1"),
    h2: document.querySelectorAll(".name"),
    h3:document.querySelectorAll(".type"),
    h4:document.querySelectorAll(".veganornot"),
    h5:document.querySelectorAll(".price"),
    img: document.querySelectorAll(".card-img"),
    gallery: document.querySelector(".flex-container"),
    button:document.getElementById("#btn"),
    text:document.querySelector("#text"),
    empty:document.querySelector(".nothing"),
    pic:document.querySelector(".img"),
    theme:document.querySelector(".Mystic"),
    theme2:document.querySelector(".Instinct"),
    theme3:document.querySelector(".Valor"),
    /* point:document.querySelectorAll(".point"), //gets all instances of this
    pointTwo:document.getElementById("pointTwo"), */
  };
  const DOM = {
    var1:document.querySelector(".var1"),
    var2:document.querySelector(".var2"),
    var3:document.querySelector(".var3"),
    var4:document.querySelector(".var4"),
    var5:document.querySelector(".var5"),
    var6:document.querySelector(".var6"),
    var7:document.querySelector(".var7"),
    var8:document.querySelector(".var8"),
    var9:document.querySelector(".var9"),
    var10:document.querySelector(".var10"),
    var11:document.querySelector(".var11"),
    var12:document.querySelector(".var12"),
    var13:document.querySelector(".var13"),
    var14:document.querySelector(".var14"),
    var15:document.querySelector(".var15"),
    var16:document.querySelector(".var16"),
    var17:document.querySelector(".var17"),
    var18:document.querySelector(".var18"),
  }
  export{DOMSelectors,DOM};